version: "3"

services:
  cmms-server:
    build: ./provisioning
    image: cmms
    depends_on:
      - mysql
      - node
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7@sha256:f568db3bdc3226cc28e4b148e6b9fd4e68d9c42e97a82be671bbe9eeb37ab1d5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx:latest@sha256:9af87a8467adcc5f77321b1ad97f692c909cb1a3eb1ca466b1c0e2dcdf4fe74e
    ports:
      - "80:80"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./public:/application/public:cached
    depends_on:
      - cmms-server

  node:
     image: node:latest@sha256:6d872a3999b1aac6aac87eb29a69d066b38f9421a62ab9290d9fceecc177775a
     working_dir: /app
     ports:
       - "8080:8080"
     volumes:
      - ./:/app:cached